### PR TITLE
Bugfix/responsive

### PR DESCRIPTION
**Pull request by gmougeolle**
A tiny PR for some QOL improvements : 

- Pages no longer disappear if Vue cannot compile the HTML tree
- Many responsive bugfixes, among which the return of the mobile suggest

ps : 🐴

### CODE REVIEW

**Review by maudetes — COMMENTED** [review]
Thank you for all these bug fixes ! :)

Could you please add a line in the changelog ? :)

Additionally, in my local environment (using Responsive Design Mode on Firefox), the fix on scrolling doesn't seem to work (https://github.com/etalab/data.gouv.fr/issues/353)

**Comment by gmougeolle** [comment]
> Thank you for all these bug fixes ! :)
> 
> Could you please add a line in the changelog ? :)
> 
> Additionally, in my local environment (using Responsive Design Mode on Firefox), the fix on scrolling doesn't seem to work ([etalab/data.gouv.fr#353](https://github.com/etalab/data.gouv.fr/issues/353))

Having a changelog is very fancy ! 🎩

I didn't address etalab/data.gouv.fr#353 yet, it's a pretty hard to fix problem and it will have to wait until september :/

**Comment by maudetes** [comment]
> > Thank you for all these bug fixes ! :)
> > Could you please add a line in the changelog ? :)
> > Additionally, in my local environment (using Responsive Design Mode on Firefox), the fix on scrolling doesn't seem to work ([etalab/data.gouv.fr#353](https://github.com/etalab/data.gouv.fr/issues/353))
> 
> Having a changelog is very fancy ! tophat
> 
> I didn't address [etalab/data.gouv.fr#353](https://github.com/etalab/data.gouv.fr/issues/353) yet, it's a pretty hard to fix problem and it will have to wait until september :/

Ah sorry, my mistake! It's not critical at all anyway ;)

**Review by maudetes — APPROVED** [review]
Looks good to me :)

**Comment by gmougeolle** [comment]
@abulte Howdy 🤠  ! If you want to merge this (maybe not in master directly ?), I think it's ready to see the light

**Review by abulte — APPROVED** [review]

**Pull request merged**
