### PR TITLE
Move dataset and reuse display page templates to udata

### PR DESCRIPTION
**Pull request by noirbizarre**
This pull-request make use of core update templates with etalab/udata#205

### CODE REVIEW

**Comment by davidbgk** [comment]
r+ might be worth an update in the docs?

**Comment by noirbizarre** [comment]
Which section ?

**Comment by davidbgk** [comment]
http://udata.readthedocs.org/en/latest/customize.html is pretty empty for now, that's probably a good timing to improve it!

**Comment by noirbizarre** [comment]
Yep, I will submit a pull request with updated documentation:
- customization
- installation
- development
- ...

**Pull request merged**
